main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: "MainBundle:User:login"

login_check:
    path: /login-check

logout:
    path: /logout

