<?php

namespace TB\MainBundle\Repository;

/**
 * Game_platformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Game_platformRepository extends \Doctrine\ORM\EntityRepository
{
}
